### PR TITLE
Fixed the text area appearance for mobile layouts

### PR DESCRIPTION
**Pull request by ARKEOLOGIST**
Helps solve #70. Had to be a bit creative with the TextAreaContents used in the component.

### CODE REVIEW

**Comment by ARKEOLOGIST** [comment]
@igeligel can you please have a look at this?

**Comment by igeligel** [comment]
Hey @ARKEOLOGIST Sorry for answering so late. Could you check the linting problems the GitHub bot discovered in the review?

**Comment by ARKEOLOGIST** [comment]
Hi @igeligel, I don't think this PR is relevant anymore, the changes have been addressed by #78

**Comment by ARKEOLOGIST** [comment]
OK I just had a look at #78, and I'm afraid that it doesn't quite look like the UI you actually want. This PR should solve the issue.

**Pull request closed without merging**
