### PR TITLE
Custom font

### PR DESCRIPTION
**Pull request by merelj**
PR for issue [Custom Font](https://github.com/igeligel/react-in-out-textarea/issues/8)

1st commit contains all the actual changes (component code + story)
~~2nd commit is just a result of me running `npm run lint -- --fix` since pre-commit hook would fail otherwise 😕~~ CI linter failed with this commit so I removed it. Fails anyway, tho... 

Eager to hear your feedback; from what I can gather I should also add an example in codesandbox, but I'm not sure how to do it since I'd have to use new version of this package 🤔

### CODE REVIEW

**Comment by merelj** [comment]
i've just spent 10 minutes on writing code and another 30 on trying to please the linter 😖 the worst thing is as soon as I fix the problem it demands to rewrite the very thing I've just fixed in another way...

would you mind adding some instructions on the correct workflow in `CONTRIBUTING.md` or somewhere? 🙏

**Comment by igeligel** [comment]
Actually, that code is good, but I did not describe the ticket well enough. I will merge it and create another ticket describing it a bit more in detail.

**Comment by igeligel** [comment]
@all-contributors please add @merelj  for code

**Comment by merelj** [comment]
Thank you for accepting the PR and sorry I didn't exactly get it right. 😖

I would gladly refactor it at some point in the future (not sure as to when though) if no one beats me to it 👍

**Comment by igeligel** [comment]
@merelj Noooo stress, just chilling. I could have described it better as well :) Created one follow up here already: https://github.com/igeligel/react-in-out-textarea/issues/39 feel free to have a look in the following weeks if you like

**Pull request merged**
