### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aman601**
Updated the Props section and table

Sorry about not completely finishing it, I realized I had no way to figure out the type or description of the functions (since I'm the one writing the documentation and don't use reactjs) but figured I would commit what I had anyways. It should be easy to change if others want to improve it, as the layout is complete 

Fixes some issues in #25 - Not a complete fix

### CODE REVIEW

**Comment by igeligel** [comment]
Hey @aman601 thanks for the contribution. Can you add the types and description for the rest of the properties as well? Otherwise, I cannot merge this Pull Request. If you have questions regarding any of these properties, feel free to reach out to me

**Comment by aman601** [comment]
@igeligel 
I would be happy to when I get time to look into the project more...could you help direct me in finding the rest of the types and descriptions? Should I be looking for where you use them? I am unsure of how to discover these (I don't use reactJS)...
Any suggestions are appreciated but I'll look into it more either way!

**Comment by igeligel** [comment]
No stress, I will write you a detailed guide tomorrow about it. I will assign the issue to you so no one else will work on it. I hope that's alright for you 🙂

**Comment by aman601** [comment]
That would be perfect, thank you!

**Comment by aman601** [comment]
I don't mean to pester @igeligel, but I can't figure some of these things uses out. If you could write a guide, great. If not, feel free to open the issue to others as I will not be able to fix it completely :)

**Comment by igeligel** [comment]
Ahh sorry for no answer.

So, you should have a look at the interface first defining all prop types:

```ts
export interface Props extends HTMLAttributes<HTMLDivElement> {
  inValue: string;
  outValue: string;
  onInInput: (text: string) => void;
  inOptions: InOptions;
  onInOptionsUpdate: (newInOptions: InOptions) => void;
  outOptions: OutOptions;
  onOutOptionsUpdate: (newOutOptions: OutOptions) => void;
}
```

The first thing to understand is the `onInInput`. This is basically a function that is called to listen to when the text on the left-hand side changes. So every time you type something in the left textarea this function is called with a new value.

The other important thing now is to understand what `InOptions` and `OutOptions` are. That is because `inValue` and `outValue` are described already.

The `InOptions` and `OutOptions` are defined in [./src/types.ts](https://github.com/igeligel/react-in-out-textarea/blob/master/src/types.ts) and look like this:

```ts
export interface IInOption {
  name: string;
  active: boolean;
}

export type InOptions = Array<IInOption>;

export interface IOutOption extends IInOption {
  activeClicked: boolean;
}

export type OutOptions = Array<IOutOption>;
```

So `InOptions` is a list of `IInOption`. Means an array of these objects:

```ts
const inOptions = [
  {
    name: "Chinese",
    active: true,
  },
  {
    name: "German",
    active: false,
  },
];
```

Basically represents the left side of the options you can select, in our examples, these are languages since we orientate on Google Translate. The active property describes which item is actually active (so underlined). Just one item can be active.

The out options look similar but have one quirk:

```ts
const outOptions = [
  {
    name: "Chinese",
    active: false,
    activeClicked: true,
  },
  {
    name: "German",
    active: false,
    activeClicked: false,
  },
];
```

As you can see these have one property that is differently called `activeClicked`. This is because I wanted to have a separator between a pre-selected right-hand language and an actively clicked one. You can see this for example by:

1. Go to https://caseconverter.pro/app
2. Enter the text `testCase` on the left side
3. The right case selection will switch to `kebab-case` - in that case the `active` property would be `true` but the `activeClicked` would be `false`
4. Now click on "PascalCase" -  in that case the `active` property would be `false` but the `activeClicked` would be true

Another thing are the action handlers:

So you can pass the options initially like the one above for the `inOptions`:

```ts
const inOptions = [
  {
    name: "Chinese",
    active: true,
  },
  {
    name: "German",
    active: false,
  },
];
```

Now if I would click on German the `onInOptionsUpdate` function would be called with the parameter `newInOptions` being:

```ts
[
  {
    name: "Chinese",
    active: false,
  },
  {
    name: "German",
    active: true,
  },
];
```

I hope that makes the options understandable.

**Comment by aman601** [comment]
Ok, I'm not sure how to update a pull request but I committed my changes again and I believe this pull request has been updated. It should now be complete, but please review the table

That makes much more sense, thank you. I think the thing that tripped me up the most was this notation that I don't really understand
 onInInput: (text: string) => void;

Thank you so much for your help, I do appreciate choosing to work through it with me instead of doing it yourself

**Comment by igeligel** [comment]
Hey @aman601 The Pull request looks good but there are conflicts.

There are guides out there on how to do this:

- https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github
- https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line

Would be nice if you could do that. Then I will merge your Pull Request 👍

**Comment by aman601** [comment]
Please review, but I believe I have resolved the conflict correctly. Thank you!

**Comment by igeligel** [comment]
Merged ✅ 

@all-contributors please add @aman601 for docs

**Pull request merged**
